#!/bin/bash

set -eo pipefail

#
# This script runs any post-test operations that may be needed.
#

if [[ $CIRCLE_BRANCH == "master" ]]; then

   terminus -n secrets:set "$TERMINUS_SITE.$TERMINUS_ENV" token "$GITHUB_TOKEN" --file='github-secrets.json' --clear --skip-if-empty

else

   terminus -n secrets:set "$TERMINUS_SITE.$CIRCLE_BRANCH" token "$GITHUB_TOKEN" --file='github-secrets.json' --clear --skip-if-empty

fi

